const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('mirai', {
  bootstrap: () => ipcRenderer.invoke('app:bootstrap'),
  openProjectDialog: () => ipcRenderer.invoke('dialog:open-project'),
  createProject: (payload) => ipcRenderer.invoke('project:create', payload),
  openWorkspace: (workspacePath) => ipcRenderer.invoke('workspace:open', workspacePath),
  listFiles: (workspacePath) => ipcRenderer.invoke('workspace:list-files', workspacePath),
  readFile: (payload) => ipcRenderer.invoke('workspace:read-file', payload),
  writeFile: (payload) => ipcRenderer.invoke('workspace:write-file', payload),
  writeBinaryFile: (payload) => ipcRenderer.invoke('workspace:write-binary-file', payload),
  createFile: (payload) => ipcRenderer.invoke('workspace:create-file', payload),
  createFolder: (payload) => ipcRenderer.invoke('workspace:create-folder', payload),
  renamePath: (payload) => ipcRenderer.invoke('workspace:rename-path', payload),
  deletePath: (payload) => ipcRenderer.invoke('workspace:delete-path', payload),
  snapshotPath: (payload) => ipcRenderer.invoke('workspace:snapshot-path', payload),
  trashPath: (payload) => ipcRenderer.invoke('workspace:trash-path', payload),
  searchWorkspace: (payload) => ipcRenderer.invoke('workspace:search', payload),
  replaceWorkspace: (payload) => ipcRenderer.invoke('workspace:replace', payload),
  saveSetting: (payload) => ipcRenderer.invoke('settings:save', payload),
  listInstalledExtensions: () => ipcRenderer.invoke('extensions:list-installed'),
  setExtensionEnabled: (payload) => ipcRenderer.invoke('extensions:set-enabled', payload),
  searchMarketplace: (payload) => ipcRenderer.invoke('marketplace:search', payload),
  getMarketplaceExtensionDetails: (payload) => ipcRenderer.invoke('marketplace:get-details', payload),
  installMarketplaceExtension: (payload) => ipcRenderer.invoke('marketplace:install', payload),
  uninstallMarketplaceExtension: (payload) => ipcRenderer.invoke('marketplace:uninstall', payload),
  showItemInFolder: (targetPath) => ipcRenderer.invoke('shell:show-item-in-folder', targetPath),
  listTerminals: () => ipcRenderer.invoke('terminal:list'),
  createTerminal: (payload) => ipcRenderer.invoke('terminal:create', payload),
  writeTerminal: (payload) => ipcRenderer.invoke('terminal:write', payload),
  readTerminal: (payload) => ipcRenderer.invoke('terminal:read', payload),
  killTerminal: (payload) => ipcRenderer.invoke('terminal:kill', payload),
  focusTerminal: (payload) => ipcRenderer.invoke('terminal:focus', payload),
  watchWorkspace: (payload) => ipcRenderer.invoke('workspace:watch', payload),
  unwatchWorkspace: () => ipcRenderer.invoke('workspace:unwatch'),
  onFileChanged: (callback) => ipcRenderer.on('workspace:file-changed', (_, data) => callback(data)),
  offFileChanged: () => ipcRenderer.removeAllListeners('workspace:file-changed'),

  // Agent APIs
  agentSetConfig: (config) => ipcRenderer.invoke('agent:set-config', config),
  agentGetConfig: () => ipcRenderer.invoke('agent:get-config'),
  agentTestModel: (model) => ipcRenderer.invoke('agent:test-model', model),
  agentCreateSession: (mode) => ipcRenderer.invoke('agent:create-session', mode),
  agentGetMessages: (sessionId) => ipcRenderer.invoke('agent:get-messages', sessionId),
  agentClearSession: (sessionId) => ipcRenderer.invoke('agent:clear-session', sessionId),
  agentAbort: () => ipcRenderer.invoke('agent:abort'),
  agentSend: (payload) => ipcRenderer.invoke('agent:send', payload),
  agentSetWorkspace: (wsPath, wsName) => ipcRenderer.invoke('agent:set-workspace', wsPath, wsName),
  agentListSessions: () => ipcRenderer.invoke('agent:list-sessions'),
  agentLoadSession: (sessionId) => ipcRenderer.invoke('agent:load-session', sessionId),
  agentDeleteSession: (sessionId) => ipcRenderer.invoke('agent:delete-session', sessionId),
  agentGetDiagnostics: () => ipcRenderer.invoke('agent:get-diagnostics'),
  onAgentEvent: (callback) => ipcRenderer.on('agent:event', (_, data) => callback(data)),
  offAgentEvent: () => ipcRenderer.removeAllListeners('agent:event')
});
